### ISSUE TITLE
Can we define a template to allow filter by node name?

### ISSUE THREAD

**Issue by QingsongYao** [vegasbrianc/grafana_dashboard#4]
If I want to monitor many docker hosts, I like to filter by host name.  Assuming that the metric has data cross many hosts.

**Comment by vegasbrianc** [comment]
Hi @QingsongYao Try this node-exporter image with exposes the hostname of the host. Then you can query each hostname within Grafana - https://github.com/bvis/docker-node-exporter 

Let me know if this helps.
